apiVersion: v1
kind: Service
metadata:
  name: greeting-service
  labels:
    app: greeting-service
spec:
  type: ClusterIP
  selector:
    app: greeting-service
  ports:
  - protocol: TCP
    port: 4001
    targetPort: 4001